package main

import (
	"fmt"
	"net/http"

	_ "./docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/go-chi/chi"
	"github.com/swaggo/http-swagger"
)

// @title Swagger hoge API
// @version 2.0
// @description This is a sample server Chi server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	r := chi.NewRouter()

	r.Get("/swagger/*", httpSwagger.WrapHandler)
	r.Get("/article", getArticle)

	http.ListenAndServe(":1323", r)
}

// getArticle godoc
// @Summary get a article foo
// @Description get string by ID
// @Accept  json
// @Produce  json
// @Param  id path int true "Account ID"
// @Success 200 {object} Article
// @Router /article/{id} [get]
func getArticle(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte(fmt.Sprintf("title:%s", "doc test")))
}

type Article struct {
	ID   int    `json:"id" example:"1"`
	Text string `json:"text" example:"article text"`
}
